version: '3'

services:
  frontend:
    container_name: registration_frontend
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - 3002:3000
    depends_on:
      backend:
        condition: service_healthy
  backend:
    container_name: registration_backend
    build:
      dockerfile: backend.Dockerfile
    ports:
      - 4002:4002
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4002/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:6.0.4
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/var/lib/mongo"

volumes:
  mongo: {}
